#pragma once

#define TAPPING_TERM 175
#define PERMISSIVE_HOLD
#define EE_HANDS

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_USE_MULTI_TRANSACTION

#ifdef RGBLIGHT_ENABLE
#    define RGBLIGHT_LIMIT_VAL 120
#    define RGBLIGHT_HUE_STEP 10
#    define RGBLIGHT_SAT_STEP 17
#    define RGBLIGHT_VAL_STEP 17
#endif
