model = "gpt-5.4"
model_reasoning_effort = "medium"
personality = "pragmatic"
sandbox_mode = "danger-full-access"
approval_policy = "never"
plan_mode_reasoning_effort = "high"

[mcp_servers.playwright]
args = ["@playwright/mcp@latest"]
command = "npx"

[projects."/Users/ezracerpac/Projects/Courses/PrepCourseSciCo"]
trust_level = "trusted"

[projects."/Users/ezracerpac/.local/share/chezmoi"]
trust_level = "trusted"

[projects."/Users/ezracerpac/Projects/Courses/ScientificComputing/Exercises/ex01-529793-cerpac-ezra"]
trust_level = "trusted"

[projects."/Users/ezracerpac/Projects/Courses/ScientificComputing"]
trust_level = "trusted"

[projects."/Users/ezracerpac/Projects"]
trust_level = "trusted"

[projects."/"]
trust_level = "trusted"

[projects."/Users/ezracerpac/Projects/jj-waltz"]
trust_level = "trusted"

[projects."/Users/ezracerpac/Projects/GenreModel"]
trust_level = "trusted"

[projects."/Users/ezracerpac"]
trust_level = "trusted"

[projects."/Users/ezracerpac/Projects/GenreModel.report"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"

[features]
multi_agent = true
prevent_idle_sleep = true

[apps.asdk_app_694a63a053f081918b9a3738bd3640c9]
enabled = false
disabled_reason = "user"

[apps.connector_947e0d954944416db111db556030eea6]
enabled = false
disabled_reason = "user"

[tui]
status_line = ["model-with-reasoning", "context-remaining", "current-dir"]
