return {
  -- { "xiyaowong/transparent.nvim" }, -- Not needed and performing less good then catpuchin option
  -- Configure LazyVim to load catppuccin
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin",
    },
  },
  -- Makes relative numbers go until 5
  -- {
  --   "mluders/comfy-line-numbers.nvim",
  --   opts = {
  --     labels = {
  --       "1",
  --       "2",
  --       "3",
  --       "4",
  --       "5",
  --       "11",
  --       "12",
  --       "13",
  --       "14",
  --       "15",
  --       "21",
  --       "22",
  --       "23",
  --       "24",
  --       "25",
  --       "31",
  --       "32",
  --       "33",
  --       "34",
  --       "35",
  --       "41",
  --       "42",
  --       "43",
  --       "44",
  --       "45",
  --       "51",
  --       "52",
  --       "53",
  --       "54",
  --       "55",
  --       "111",
  --       "112",
  --       "113",
  --       "114",
  --       "115",
  --       "121",
  --       "122",
  --       "123",
  --       "124",
  --       "125",
  --       "131",
  --       "132",
  --       "133",
  --       "134",
  --       "135",
  --       "141",
  --       "142",
  --       "143",
  --       "144",
  --       "145",
  --       "151",
  --       "152",
  --       "153",
  --       "154",
  --       "155",
  --       "211",
  --       "212",
  --       "213",
  --       "214",
  --       "215",
  --       "221",
  --       "222",
  --       "223",
  --       "224",
  --       "225",
  --       "231",
  --       "232",
  --       "233",
  --       "234",
  --       "235",
  --       "241",
  --       "242",
  --       "243",
  --       "244",
  --       "245",
  --       "251",
  --       "252",
  --       "253",
  --       "254",
  --       "255",
  --     },
  --
  --     -- Line numbers will be completely hidden for the following file/buffer types
  --     hidden_file_types = { "undotree" },
  --     hidden_buffer_types = { "terminal" },
  --   },
  -- },
  -- Configure Catppuccin with custom highlights
  {
    "catppuccin/nvim",
    name = "catppuccin",
    opts = {
      transparent_background = true,
      custom_highlights = {
        LineNr = { fg = "#a6adc8" }, -- Lighter color
        CursorLineNr = { fg = "#cdd6f4" }, -- Even lighter for active line
        Visual = { bg = "#585b70", fg = "#cdd6f4" }, -- Brighter visual selection
      },
      integrations = {
        aerial = true,
        alpha = true,
        -- blink = true,
        cmp = true,
        dashboard = true,
        fzf = true,
        grug_far = true,
        gitsigns = true,
        headlines = true,
        illuminate = true,
        indent_blankline = { enabled = true },
        flash = true,
        lsp_trouble = true,
        mason = true,
        markdown = true,
        mini = true,
        native_lsp = {
          enabled = true,
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },
          },
        },
        navic = { enabled = true, custom_bg = "lualine" },
        neotest = true,
        noice = true,
        notify = true,
        overseer = true,
        semantic_tokens = true,
        snacks = true,
        telescope = true,
        treesitter = true,
        treesitter_context = true,
        which_key = true,
      },
    },
  },
}
