#!/usr/bin/env bash

set -euo pipefail
umask 077

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=setup-scripts/local/common
source "${SCRIPT_DIR}/common"
require_setup_profile workstation
require_macos

readonly expected_revision="0c0671cc593a556a1627a10aee601671e6cbeb3e"
readonly expected_version="0.21.3-PR2245-Local"
readonly source_dir="${AEROSPACE_SOURCE_DIR:-${HOME}/Projects/Tools/AeroSpace}"
readonly app_path="/Applications/AeroSpace.app"
readonly stage_root="${AEROSPACE_STAGE_ROOT:-${HOME}/.local/state/aerospace-pr2245/staged}"
readonly revision_short="${expected_revision:0:8}"
readonly stage_path="${stage_root}/${expected_version}-${revision_short}"

setup_error() {
    printf 'aerospace: %s\n' "$*" >&2
}

require_command() {
    local command_name="${1:?command required}"
    mise_exec which "$command_name" >/dev/null 2>&1 || {
        setup_error "required command not found through mise: ${command_name}"
        return 1
    }
}

signature_authority() {
    local path="${1:?signed path required}"
    /usr/bin/codesign -dv --verbose=4 "$path" 2>&1 |
        sed -n 's/^Authority=//p' |
        head -n 1
}

validate_stage() {
    local stage="${1:?stage path required}"
    local bundle="${stage}/AeroSpace.app"
    local app_binary="${bundle}/Contents/MacOS/AeroSpace"
    local cli="${stage}/aerospace"
    local app_version bundle_id

    [[ -d "$bundle" && -x "$app_binary" && -x "$cli" ]] || return 1
    app_version="$(/usr/bin/plutil -extract CFBundleShortVersionString raw -o - "${bundle}/Contents/Info.plist" 2>/dev/null)" || return 1
    bundle_id="$(/usr/bin/plutil -extract CFBundleIdentifier raw -o - "${bundle}/Contents/Info.plist" 2>/dev/null)" || return 1
    [[ "$app_version" == "$expected_version" && "$bundle_id" == bobko.aerospace ]] || return 1

    /usr/bin/strings "$app_binary" | grep -F "$expected_revision" >/dev/null || return 1
    /usr/bin/strings "$cli" | grep -F "$expected_revision" >/dev/null || return 1
    [[ "$(signature_authority "$bundle")" == "$signing_identity" ]] || return 1
    [[ "$(signature_authority "$cli")" == "$signing_identity" ]] || return 1
    /usr/bin/codesign --verify --deep --strict "$bundle" >/dev/null 2>&1 || return 1
    /usr/bin/codesign --verify --strict "$cli" >/dev/null 2>&1 || return 1
}

require_command git
require_command bash
require_command swift
require_command xcodebuild

[[ -d "$source_dir" ]] || {
    setup_error "source checkout not found: ${source_dir}"
    exit 1
}

source_revision="$(mise_exec git -C "$source_dir" rev-parse HEAD)"
[[ "$source_revision" == "$expected_revision" ]] || {
    setup_error "source revision is ${source_revision}; expected ${expected_revision}"
    exit 1
}
source_changes="$(mise_exec git -C "$source_dir" status --porcelain=v1 --untracked-files=all)"
[[ -z "$source_changes" ]] || {
    setup_error "source checkout has changes; preserve and reconcile them before building"
    printf '%s\n' "$source_changes" >&2
    exit 1
}

signing_identity="${AEROSPACE_CODESIGN_IDENTITY:-}"
if [[ -z "$signing_identity" && -d "$app_path" ]]; then
    signing_identity="$(signature_authority "$app_path" || true)"
fi
[[ -n "$signing_identity" ]] || {
    setup_error "set AEROSPACE_CODESIGN_IDENTITY or keep the signed active app available to identify its signer"
    exit 1
}
identity_matches="$(/usr/bin/security find-identity -v -p codesigning | grep -F "\"${signing_identity}\"" || true)"
[[ "$(printf '%s\n' "$identity_matches" | awk 'NF { n += 1 } END { print n + 0 }')" -eq 1 ]] || {
    setup_error "signing identity is missing or ambiguous in the keychain: ${signing_identity}"
    exit 1
}

if [[ -e "$stage_path" ]]; then
    if validate_stage "$stage_path"; then
        printf 'AeroSpace %s is already staged at %s\n' "$expected_version" "$stage_path"
        exit 0
    fi
    setup_error "staging destination exists but does not match the expected build; preserving it: ${stage_path}"
    exit 1
fi

mkdir -p "$stage_root"
build_root="$(mktemp -d "${stage_root}/.build.XXXXXX")"
cleanup() {
    [[ -n "${build_root:-}" && -d "$build_root" ]] && rm -rf -- "$build_root"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

source_copy="${build_root}/source"
mkdir -p "$source_copy"
mise_exec git -C "$source_dir" archive --format=tar "$expected_revision" | tar -xf - -C "$source_copy"

echo "Generating version metadata for ${expected_version} (${expected_revision}) in an isolated source copy"
mise_exec bash "${source_copy}/generate.sh" \
    --build-version "$expected_version" \
    --codesign-identity "$signing_identity" \
    --ignore-xcodeproj \
    --ignore-cmd-help
cat > "${source_copy}/Sources/Common/gitHashGenerated.swift" <<EOF
// FILE IS GENERATED BY generate.sh
public let gitHash = "${expected_revision}"
public let gitShortHash = "${revision_short}"
EOF

echo "Building the arm64 CLI and signed Release app into a private staging directory"
mise_exec swift build \
    --package-path "$source_copy" \
    --scratch-path "${build_root}/swift-build" \
    --configuration release \
    --arch arm64 \
    --product aerospace \
    -Xswiftc -warnings-as-errors
mise_exec xcodebuild \
    -project "${source_copy}/xcode/AeroSpace.xcodeproj" \
    -scheme AeroSpace \
    -destination 'generic/platform=macOS' \
    -configuration Release \
    -derivedDataPath "${build_root}/xcode-build" \
    CODE_SIGN_IDENTITY="$signing_identity" \
    MARKETING_VERSION="$expected_version" \
    build

cli_build="${build_root}/swift-build/apple/Products/Release/aerospace"
app_build="${build_root}/xcode-build/Build/Products/Release/AeroSpace.app"
require_file "$cli_build"
[[ -d "$app_build" ]] || {
    setup_error "Xcode did not produce the expected app bundle: ${app_build}"
    exit 1
}

stage_temp="${build_root}/stage"
mkdir -p "$stage_temp"
/usr/bin/ditto "$app_build" "${stage_temp}/AeroSpace.app"
/usr/bin/install -m 0755 "$cli_build" "${stage_temp}/aerospace"
/usr/bin/codesign --force --sign "$signing_identity" --timestamp=none "${stage_temp}/aerospace" >/dev/null

cat > "${stage_temp}/BUILD-INFO" <<EOF
version=${expected_version}
revision=${expected_revision}
signing_identity=${signing_identity}
architecture=arm64
EOF

if ! validate_stage "$stage_temp"; then
    setup_error "staged app or CLI failed version, revision, signature, or bundle validation"
    exit 1
fi

if ! mv -n "$stage_temp" "$stage_path"; then
    setup_error "could not publish the validated stage at ${stage_path}"
    exit 1
fi
if ! validate_stage "$stage_path"; then
    setup_error "staging destination changed during publication; preserving it for inspection: ${stage_path}"
    exit 1
fi

printf 'Built and staged AeroSpace %s (%s) at %s\n' "$expected_version" "$revision_short" "$stage_path"
echo 'No active app, CLI, window-manager process, or login item was changed.'
