VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes

RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no

MOUSEKEY_ENABLE = no
OLED_ENABLE = no
EXTRAKEY_ENABLE = yes
COMBO_ENABLE = no
TAP_DANCE_ENABLE = yes

QMK_SETTINGS = no
