complete -c dots -f
complete -c dots -n 'not __fish_seen_subcommand_from up update status plan test remote bundle apply bootstrap backup restore add remove uninstall help' -a 'up status plan test remote bundle apply bootstrap backup restore add remove uninstall help'
complete -c dots -n '__fish_seen_subcommand_from test' -a 'python node shell lua' -d 'Test suite'
complete -c dots -n '__fish_seen_subcommand_from add' -l base -d 'Record in the shared base'
complete -c dots -n '__fish_seen_subcommand_from add' -l profile -x -a 'workstation nas' -d 'Record in this role'
complete -c dots -n '__fish_seen_subcommand_from add' -l path -r -d 'Record in an explicit config file'
complete -c dots -n '__fish_seen_subcommand_from add' -l asset -x -d 'GitHub release asset name or glob (one repository URL)'
complete -c dots -n '__fish_seen_subcommand_from remove uninstall' -l base -d 'Remove from shared config'
complete -c dots -n '__fish_seen_subcommand_from remove uninstall' -l profile -x -a 'workstation nas' -d 'Remove from this role'
complete -c dots -n '__fish_seen_subcommand_from remove uninstall' -l path -r -d 'Remove from an explicit config file'
complete -c dots -n '__fish_seen_subcommand_from remove uninstall' -l dry-run -d 'Preview without removing software or declarations'
complete -c dots -n '__fish_seen_subcommand_from remove uninstall' -l keep-installed -d 'Remove declarations and keep installed software'
complete -c dots -n '__fish_seen_subcommand_from remote' -l profile -x -a 'workstation nas'
complete -c dots -n '__fish_seen_subcommand_from remote bootstrap' -l dry-run -d 'Preview without applying resources'
complete -c dots -n '__fish_seen_subcommand_from bootstrap' -l bundle -r -d 'Encrypted bootstrap bundle'
complete -c dots -n '__fish_seen_subcommand_from bootstrap' -l identity -r -d 'External age identity'
complete -c dots -n '__fish_seen_subcommand_from bootstrap' -l restore -x -d 'Existing machine identity to restore'
complete -c dots -s h -l help -d 'Show help'
